Repository ember-cli/ember-cli, pull requests merged in 2018-02, with the labels that each got.

#7601 blueprints/addon: Replace `test` with `test:all`
  blueprints/addon/files/README.md
  blueprints/addon/index.js
  tests/fixtures/addon/npm/README.md
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/addon/yarn/package.json
  tests/unit/blueprints/addon-test.js
Labels: Enhancement

#7627 Fixing test fixtures from 3.0.0 release
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: Internal

#7626 Fix 'const' declarations in non-strict mode are not supported
  blueprints/app/files/config/targets.js
Labels: Bug

#7631 Fix failing tests on `beta` branch
  lib/experiments/index.js
  tests/unit/models/project-test.js
Labels: Internal

#7630 Add `blockchain` support
  package.json
Labels: Enhancement

#7635 Packaged Bower
  lib/broccoli/default-packager.js
  lib/broccoli/ember-app.js
  tests/unit/broccoli/default-packager/bower-test.js
Labels: Internal
