Repository ember-cli/ember-cli, pull requests merged in 2018-05, with the labels that each got.

#7801 Update node support policy docs.
  docs/node-support.md
Labels: Documentation

#7808 Drop Node 4 support
  .travis.yml
  appveyor.yml
  blueprints/addon/files/.travis.yml
  blueprints/app/files/package.json
  blueprints/module-unification-addon/files/.travis.yml
  blueprints/module-unification-app/files/package.json
  package.json
  tests/fixtures/addon/npm/.travis.yml
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/.travis.yml
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/.travis.yml
  tests/fixtures/module-unification-addon/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#7803 Migrate to using Travis stages.
  .travis.yml
  CONTRIBUTING.md
  docs/experiments.md
  lib/experiments/index.js
  lib/utilities/platform-checker.js
  tests/experiments.js
Labels: Internal

#7830 Make sure `package` hook warning is shown properly
  lib/broccoli/ember-app.js
Labels: Packager

#7829 Move styles from add-ons under `app-name`
  lib/broccoli/ember-app.js
  tests/unit/broccoli/ember-app-test.js
Labels: Packager

#7833 blueprints/addon: Add `yarn.lock` file to `.npmignore`
  blueprints/addon/files/npmignore
Labels: Enhancement

#7621 Take newer symlink-or-copy
  package.json
  yarn.lock
Labels: Bug

#7733 Prompt to perform `yarn` in case of missing deps and present yarn.lock
  lib/models/installation-checker.js
Labels: Enhancement

#7836 tests: Increase timeout for linting tests
  tests/unit/lint-test.js
Labels: Internal

#7560 Migrate to new format for mode specific arguments in testem config.
  blueprints/app/files/testem.js
Labels: Enhancement

#7780 run `eslint .` plus .eslintignore
  blueprints/addon/index.js
  blueprints/app/files/.eslintignore
  blueprints/app/files/gitignore
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/.eslintignore
  blueprints/module-unification-app/files/gitignore
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/.eslintignore
  tests/fixtures/module-unification-addon/.gitignore
  tests/fixtures/module-unification-addon/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
  tests/unit/blueprints/addon-test.js
Labels: Needs Submitter Response
