Repository ember-cli/ember-cli, pull requests merged in 2018-09, with the labels that each got.

#8021 RELEASE.md: Change from Slack to Discord
  RELEASE.md
Labels: Documentation

#8047 Fix transforms for tests
  lib/broccoli/default-packager.js
  tests/unit/broccoli/default-packager/tests-test.js
Labels: Bug

#8032 Update minimum broccoli-viz version
  PERF_GUIDE.md
Labels: Documentation

#8064 Update `qunit-dom` to v0.8.0
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#8062 Add `yarn.lock` to `.npmignore`
  .npmignore
Labels: Enhancement
