Repository ember-cli/ember-cli, pull requests merged in 2018-12, with the labels that each got.

#8240 Reset blueprint's ignoredFiles
  lib/models/blueprint.js
  tests/acceptance/addon-generate-test.js
  tests/integration/models/blueprint-test.js
Labels: Bug

#8277 DefaultPackager: Move `addon-test-support` out of the `tests` folder
  lib/broccoli/default-packager.js
  tests/unit/broccoli/default-packager/tests-test.js
Labels: Bug, Packager

#8278 DefaultPackager: Fix addon preprocessing
  lib/broccoli/default-packager.js
Labels: Bug, Packager

#8279 CHANGELOG: Drop releases before v2.8.0
  CHANGELOG.md
Labels: Documentation

#8284 tests/package-cache: Increase test timeout
  tests/unit/utilities/package-cache-test.js
Labels: Internal

#8287 blueprints/app: Update Ember and Ember Data to v3.6.0
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#8175 Do not watch `tests` directory when tests are disabled
  lib/broccoli/ember-app.js
  tests/unit/broccoli/ember-app-test.js
Labels: Bug

#8296 Add ember-source@3.4 LTS ember-try scenario.
  blueprints/addon/files/.travis.yml
  blueprints/addon/files/addon-config/ember-try.js
  blueprints/module-unification-addon/files/.travis.yml
  blueprints/module-unification-addon/files/addon-config/ember-try.js
  tests/fixtures/addon/npm/.travis.yml
  tests/fixtures/addon/npm/config/ember-try.js
  tests/fixtures/addon/yarn/.travis.yml
  tests/fixtures/addon/yarn/config/ember-try.js
Labels: Enhancement

#8308 ignore .env* files
  blueprints/addon/files/npmignore
  blueprints/app/files/gitignore
  blueprints/module-unification-addon/files/npmignore
  blueprints/module-unification-app/files/gitignore
Labels: Enhancement

#8307 Upgrade ember-cli-blueprint-test-helpers
  package.json
  yarn.lock
Labels: Internal

#8309 fix(blueprints/addon): add contributing section
  blueprints/addon/files/README.md
  blueprints/module-unification-addon/files/README.md
  tests/fixtures/addon/npm/README.md
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/module-unification-addon/README.md
Labels: Documentation

#6867 Use `encode/decodeURIComponent()` for `meta` tag config
  lib/broccoli/app-config-from-meta.js
  lib/broccoli/ember-app.js
  lib/utilities/ember-app-utils.js
  tests/unit/broccoli/default-packager/ember-cli-internal-test.js
  tests/unit/broccoli/ember-app-test.js
  tests/unit/utilities/ember-app-utils-test.js
Labels: Internal

#8313 bump ember-ajax to v4
  blueprints/app/files/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: Enhancement

#8052 Use non-greedy pattern for `{{content-for}}`
  lib/utilities/ember-app-utils.js
  tests/unit/utilities/ember-app-utils-test.js
Labels: Bug

#8286 Provide a compatibility section in addon READMEs
  blueprints/addon/files/README.md
  blueprints/module-unification-addon/files/README.md
  tests/fixtures/addon/npm/README.md
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/module-unification-addon/README.md
Labels: Documentation
