Repository ember-cli/ember-cli, pull requests merged in 2018-10, with the labels that each got.

#8096 Use regex to parse /livereload urls
  lib/tasks/server/livereload-server.js
  lib/tasks/server/middleware/proxy-server/index.js
  lib/utilities/is-live-reload-request.js
  tests/unit/tasks/server/middleware/proxy-server-test.js
  tests/unit/utilities/is-live-reload-request-test.js
Labels: Bug

#8116 Only assert on fallback messaging when BROCCOLI_2 enabled.
  tests/unit/broccoli/builder-test.js
Labels: Internal

#8120 Adjust release instructions
  RELEASE.md
Labels: Documentation

#8126 Removed the usage of `td.replace('string', ...)`
  tests/unit/cli/cli-test.js
  tests/unit/models/builder-test.js
Labels: Internal

#7974 Prevent double builds in CI for branches pushed by owner.
  blueprints/addon/files/.travis.yml
  tests/fixtures/addon/npm/.travis.yml
  tests/fixtures/addon/yarn/.travis.yml
Labels: Enhancement

#8130 Backport livereload prefix scoping fixes to release.
  lib/tasks/server/livereload-server.js
  lib/tasks/server/middleware/proxy-server/index.js
  lib/utilities/is-live-reload-request.js
  tests/unit/tasks/server/middleware/proxy-server-test.js
  tests/unit/utilities/is-live-reload-request-test.js
Labels: Bug

#8086 Prefer walk-sync for AssetPrinterSize (speeds things up)
  lib/models/asset-size-printer.js
  tests/unit/models/asset-size-printer-test.js
Labels: Internal

#8108 put package-info-cache warnings under DEBUG control
  lib/models/package-info-cache/index.js
  lib/models/package-info-cache/package-info.js
Labels: Internal

#8112 fixing smoke test failure for tmp directory
  tests/acceptance/smoke-test-slow.js
Labels: Internal

#8145 remove trailing comma
  blueprints/addon/files/addon-config/ember-try.js
  tests/fixtures/addon/npm/config/ember-try.js
  tests/fixtures/addon/yarn/config/ember-try.js
Labels: Enhancement

#8138 Remove ember-ajax from addon blueprint
  blueprints/addon/index.js
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/module-unification-addon/package.json
Labels: Enhancement
