Repository ember-cli/ember-cli, pull requests merged in 2018-11, with the labels that each got.

#8202 Specify explicit ember-cli version in project update instructions
  RELEASE.md
Labels: Documentation

#7958 Gather doc files in docs directory
  ADDON_HOOKS.md
  docs/analytics.md
  docs/architecture.md
  docs/assets/architecture/Ember-CLI architecture.png
  docs/assets/architecture/Ember-CLI architecture.xml
  docs/assets/architecture/README.md
  docs/brocfile-transition.md
  docs/build-pipeline-debugging.md
  docs/code-coverage.md
  docs/error-propagation.md
  docs/perf-guide.md
  docs/sourcemaps.md
  tests/unit/tasks/serve-test.js
Labels: Documentation

#8209 Skip broken smoke tests
  tests/acceptance/smoke-test-slow.js
Labels: Internal

#8207 TravisCI: Remove deprecated `sudo` mode
  .travis.yml
Labels: Internal

#8091 target new broccoli-concat
  package.json
  yarn.lock
Labels: Internal

#8203 Move contribution info away from README to CONTRIBUTING
  blueprints/addon/files/CONTRIBUTING.md
  blueprints/addon/files/README.md
  blueprints/addon/files/npmignore
  blueprints/module-unification-addon/files/CONTRIBUTING.md
  blueprints/module-unification-addon/files/README.md
  blueprints/module-unification-addon/files/npmignore
  tests/acceptance/new-test.js
  tests/fixtures/addon/npm/CONTRIBUTING.md
  tests/fixtures/addon/npm/README.md
  tests/fixtures/addon/yarn/CONTRIBUTING.md
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/module-unification-addon/CONTRIBUTING.md
  tests/fixtures/module-unification-addon/README.md
Labels: Enhancement

#8171 Add `--ssl` options to `ember test`
  lib/commands/serve.js
  lib/commands/test.js
  lib/tasks/test.js
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
  tests/unit/tasks/test-test.js
Labels: Enhancement

#8165 remove unused "ember-default" scenario
  blueprints/addon/files/addon-config/ember-try.js
  tests/fixtures/addon/npm/config/ember-try.js
  tests/fixtures/addon/yarn/config/ember-try.js
Labels: Enhancement

#8206 remove duplicate eslint fixtures
  tests/acceptance/new-test.js
  tests/fixtures/addon/.eslintrc.js
  tests/fixtures/addon/yarn/.eslintrc.js
  tests/fixtures/app/.eslintrc.js
  tests/fixtures/app/yarn/.eslintrc.js
  tests/fixtures/module-unification-app/.eslintrc.js
  tests/fixtures/module-unification-app/yarn/.eslintrc.js
Labels: Internal

#8177 Add documentation for various properties on `Addon`
  lib/models/addon.js
Labels: Documentation
