Repository ember-cli/ember-cli, pull requests merged in 2019-03, with the labels that each got.

#8470 Remove obsolete `BROCCOLI_2` experiment
  .travis.yml
  lib/experiments/index.js
  lib/models/builder.js
  tests/unit/broccoli/builder-test.js
  tests/unit/experiments-test.js
  tests/unit/models/builder-test.js
Labels: Enhancement

#8471 Replace `mocha-eslint` with raw ESLint
  .eslintrc.js
  .gitignore
  .travis.yml
  blueprints/addon-import/index.js
  lib/broccoli/ember-app.js
  lib/models/blueprint.js
  lib/models/file-info.js
  lib/tasks/server/livereload-server.js
  lib/utilities/get-option-args.js
  package.json
  tests/.eslintrc.js
  tests/helpers/mock-project.js
  tests/runner.js
  tests/unit/lint-test.js
  yarn.lock
Labels: Internal

#8473 Improve CI config
  .travis.yml
  .travis/deploy.sh
Labels: Internal

#8482 Update ember-ajax in blueprints and tests
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Bug

#8418 start the add-to-output-repo extraction
  dev/add-to-output-repo.js
  dev/add-to-output-repos.js
Labels: Internal

#8505 Fix broken `FSTree.fromEntries()` invocations
  lib/tasks/server/livereload-server.js
  tests/unit/tasks/server/livereload-server-test.js
Labels: Internal

#8459 Drop Node 6 support
  .travis.yml
  appveyor.yml
  package.json
Labels: Enhancement
