Repository ember-cli/ember-cli, pull requests merged in 2019-02, with the labels that each got.

#8383 Update `ember-welcome-page` usage to angle brackets
  blueprints/app/files/app/templates/application.hbs
  blueprints/module-unification-app/files/src/ui/routes/application/template.hbs
  tests/acceptance/new-test.js
  tests/fixtures/addon/yarn/tests/dummy/app/templates/application.hbs
  tests/fixtures/app/yarn/app/templates/application.hbs
  tests/fixtures/module-unification-addon/yarn/tests/dummy/src/ui/routes/application/template.hbs
  tests/fixtures/module-unification-app/yarn/src/ui/routes/application/template.hbs
Labels: Enhancement

#8100 Attempt to fix CI with npm@5 and npm@6.
  lib/tasks/npm-task.js
Labels: Internal

#8456 Fix default-packager styles tests
  tests/unit/broccoli/default-packager/styles-test.js
Labels: Internal

#8466 Skip flaky `serve-wasm` test on Node 6
  tests/acceptance/smoke-test-slow.js
Labels: Internal

#8460 blueprints: Update `ember-qunit` to v4.4.1
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/acceptance/brocfile-smoke-test-slow.js
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/npm/package.json
  tests/fixtures/module-unification-addon/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#8467 Ensure npm version is available during ember new / ember install foo.
  lib/tasks/npm-task.js
Labels: Bug
