Repository ember-cli/ember-cli, pull requests merged in 2019-05, with the labels that each got.

#8621 project.findAddonByName was intended to be public
  lib/models/project.js
Labels: Documentation

#8627 blueprints/app: Update `ember-cli-babel` to v7.7.3
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/npm/package.json
  tests/fixtures/module-unification-addon/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#8656 fix: reset resolve-package-path caches in PackageInfoCache._clear()
  lib/models/package-info-cache/index.js
Labels: Bug

#8661 Remove extra Node 10 Travis CI job.
  .travis.yml
Labels: Internal
