Repository ember-cli/ember-cli, pull requests merged in 2019-01, with the labels that each got.

#8329 livereload-server: Fix logger output
  lib/tasks/server/livereload-server.js
Labels: Internal

#8328 tasks/server: Remove obsolete `exists-sync` dependency declaration
  lib/tasks/server/middleware/tests-server/package.json
Labels: Internal

#8330 blueprints/app/gitignore: Ignore Yarn PnP files
  blueprints/app/files/gitignore
  blueprints/module-unification-app/files/gitignore
Labels: Enhancement

#8331 Update `ember-cli-dependency-checker` to v3.1.0
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/npm/package.json
  tests/fixtures/module-unification-addon/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
  tests/helpers/default-packager.js
Labels: Enhancement

#8323 Fetch dynamically the `ember-source` version for MU blueprints
  blueprints/module-unification-addon/index.js
  blueprints/module-unification-app/files/package.json
  blueprints/module-unification-app/index.js
  package.json
  tests/acceptance/new-test.js
  tests/fixtures/module-unification-addon/npm/package.json
  tests/fixtures/module-unification-addon/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
  yarn.lock
Labels: Enhancement

#8299 remove ember-lts-2.16 ember-try scenario
  blueprints/addon/files/.travis.yml
  blueprints/addon/files/addon-config/ember-try.js
  blueprints/module-unification-addon/files/.travis.yml
  blueprints/module-unification-addon/files/addon-config/ember-try.js
  tests/fixtures/addon/npm/.travis.yml
  tests/fixtures/addon/npm/config/ember-try.js
  tests/fixtures/addon/yarn/.travis.yml
  tests/fixtures/addon/yarn/config/ember-try.js
Labels: Enhancement

#8335 Fix MU test fixtures
  tests/fixtures/module-unification-addon/npm/.travis.yml
  tests/fixtures/module-unification-addon/npm/config/ember-try.js
  tests/fixtures/module-unification-addon/yarn/.travis.yml
  tests/fixtures/module-unification-addon/yarn/README.md
  tests/fixtures/module-unification-addon/yarn/config/ember-try.js
Labels: Internal

#8327 Improve `ember-cli` entry file
  bin/ember
Labels: Enhancement

#8351 Update Ember and Ember Data to v3.7.0
  blueprints/app/files/package.json
  blueprints/module-unification-app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
Labels: Enhancement

#8352 Fix `relative-module-paths` caching
  lib/broccoli/babel-process-modules-only.js
  lib/utilities/relative-module-paths.js
  package.json
  yarn.lock
Labels: Bug

#8357 blueprints/addon: Fix incorrect job formatting in `.travis.yml` config
  blueprints/addon/files/.travis.yml
  tests/fixtures/addon/npm/.travis.yml
  tests/fixtures/addon/yarn/.travis.yml
Labels: Bug

#8373 package-info-cache: Add `heimdalljs-logger` logging
  lib/models/package-info-cache/index.js
  lib/models/package-info-cache/package-info.js
Labels: Internal
