Repository ember-cli/ember-cli, pull requests merged in 2019-06, with the labels that each got.

#8675 [beta] Gather hardware information when creating instrumentation summaries.
  lib/models/hardware-info.js
  lib/models/instrumentation.js
  tests/unit/models/hardware-info-test.js
  tests/unit/models/instrumentation-test.js
Labels: Enhancement

#8679 Adding change logging for backwards compatibility
  lib/models/server-watcher.js
  lib/models/watcher.js
  tests/unit/models/watcher-test.js
Labels: Blocking

#8588 [dx] Detail app / addon creation messages
  blueprints/addon/index.js
  blueprints/app/index.js
  lib/commands/init.js
  lib/tasks/git-init.js
  lib/tasks/npm-task.js
  lib/utilities/prepend-emoji.js
  tests/unit/tasks/git-init-test.js
Labels: Enhancement

#8653 Use absolute link to Contribution.md
  README.md
Labels: Documentation
