Repository ember-cli/ember-cli, pull requests merged in 2019-12, with the labels that each got.

#8949 Use GitHub Actions for CI
  .github/workflows/ci.yml
Labels: Internal

#8965 Update ember-resolver to v7.0.0.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/simple/package.json
  tests/fixtures/addon/with-app-styles/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/brocfile-tests/query/package.json
  tests/fixtures/project-with-handlebars/package.json
  tests/unit/models/project-test.js
Labels: Enhancement

#8967 Update GitHub Actions setup to use TAP output.
  tests/runner.js
Labels: Internal

#8968 Fix PackageInfoCache assertions to work properly in Windows.
  tests/unit/models/package-info-cache/package-info-cache-test.js
Labels: Internal

#8964 Add support for `ember new @scope-here/name-here`.
  lib/commands/init.js
  lib/commands/new.js
  lib/tasks/create-and-step-into-directory.js
  lib/utilities/valid-project-name.js
  tests/acceptance/new-test.js
  tests/unit/utilities/valid-project-name-test.js
Labels: Bug

#8929 Drop Node 11 support in generated apps and addons
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: breaking

#8981 fix env var typo
  .github/workflows/ci.yml
Labels: Internal
