Repository ember-cli/ember-cli, pull requests merged in 2019-04, with the labels that each got.

#8556 Ensure packager respects source map config when concatting
  lib/broccoli/default-packager.js
  tests/unit/broccoli/default-packager/tests-test.js
Labels: Bug

#8552 analytics-test: Use async/await
  tests/unit/analytics-test.js
Labels: Internal

#8557 #8511 Modernize install-blueprint-task.js test
  tests/unit/tasks/install-blueprint-test.js
Labels: Internal

#8572 use eslint-plugin-node v8 in blueprints
  blueprints/addon/index.js
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/module-unification-addon/npm/package.json
  tests/fixtures/module-unification-addon/yarn/package.json
  tests/unit/blueprints/addon-test.js
Labels: Enhancement

#8205 run eslint-plugin-node on apps
  blueprints/addon/index.js
  blueprints/app/files/.eslintrc.js
  blueprints/app/files/package.json
  blueprints/module-unification-addon/files/.eslintrc.js
  blueprints/module-unification-app/files/.eslintrc.js
  blueprints/module-unification-app/files/package.json
  tests/fixtures/app/.eslintrc.js
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  tests/fixtures/module-unification-addon/.eslintrc.js
  tests/fixtures/module-unification-app/.eslintrc.js
  tests/fixtures/module-unification-app/npm/package.json
  tests/fixtures/module-unification-app/yarn/package.json
  tests/unit/blueprints/addon-test.js
Labels: Enhancement

#8595 [ENHANCEMENT] Project#config should use EMBER_ENV as default environment when none is passed in
  lib/models/project.js
  tests/unit/models/project-test.js
Labels: Bug
