Repository ember-cli/ember-cli, pull requests merged in 2020-05, with the labels that each got.

#9208 Update blueprint dependencies to latest versions.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9210 Revert "test version-utils"
  lib/utilities/version-utils.js
  tests/unit/utilities/version-utils-test.js
Labels: internal

#9212 Ensure that the captured exit is released.
  lib/cli/index.js
Labels: bug

#9209 Create small development script to update blueprint dependencies.
  blueprints/addon/additional-dev-dependencies.json
  blueprints/addon/index.js
  dev/update-blueprint-dependencies.js
  package.json
  yarn.lock
Labels: internal

#9215 Handle unexpected errors in development mode proxy
  lib/tasks/server/middleware/proxy-server/index.js
Labels: bug

#9218 Update eslint to 7.0.0.
  blueprints/app/files/.eslintrc.js
  blueprints/app/files/package.json
  package.json
  tests/fixtures/addon/.eslintrc.js
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/.eslintrc.js
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  yarn.lock
Labels: enhancement

#9219 Add ability to pass `--filter` to `dev/update-blueprint-dependencies.js`
  dev/update-blueprint-dependencies.js
Labels: internal

#9205 Pass options to middleware
  lib/tasks/test.js
  tests/fixtures/tasks/testem-config/testem-dummy.json
  tests/unit/tasks/test-test.js
Labels: enhancement

#9240 Ensure `ember serve` property waits for the serve task.
  lib/commands/serve.js
  tests/unit/commands/serve-test.js
Labels: bug

#9238 Add config/ember-cli-update.json to app and addon blueprints.
  blueprints/addon/index.js
  blueprints/app/files/config/ember-cli-update.json
  blueprints/app/index.js
  dev/update-blueprint-dependencies.js
  tests/acceptance/new-test.js
  tests/fixtures/addon/defaults/.travis.yml
  tests/fixtures/addon/defaults/CONTRIBUTING.md
  tests/fixtures/addon/defaults/README.md
  tests/fixtures/addon/defaults/config/ember-try.js
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/defaults/tests/dummy/app/templates/application.hbs
  tests/fixtures/addon/defaults/tests/dummy/config/ember-cli-update.json
  tests/fixtures/addon/yarn/tests/dummy/config/ember-cli-update.json
  tests/fixtures/app/defaults/.travis.yml
  tests/fixtures/app/defaults/README.md
  tests/fixtures/app/defaults/app/templates/application.hbs
  tests/fixtures/app/defaults/config/ember-cli-update.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/npm/config/ember-cli-update.json
  tests/fixtures/app/yarn/config/ember-cli-update.json
Labels: enhancement
