Repository ember-cli/ember-cli, pull requests merged in 2020-02, with the labels that each got.

#9013 Remove useless line break in `.editorconfig` file
  blueprints/app/files/.editorconfig
Labels: Bug

#9026 Add @glimmer/tracking to default blueprint.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: Bug

#8905 Use production environment for `npm run build` / `yarn build` by default
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: Enhancement

#9035 Fix tests failing due to chalk update.
  tests/unit/utilities/markdown-color-test.js
Labels: Internal

#9037 Update Ember and Ember Data to 3.17 betas.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: Enhancement

#9039 Remove long enabled EMBER_CLI_SYSTEM_TEMP experiment.
  .github/workflows/ci.yml
  .travis.yml
  lib/experiments/index.js
  lib/models/builder.js
  lib/utilities/attempt-never-index.js
  tests/unit/experiments-test.js
  tests/unit/models/builder-test.js
  tests/unit/utilities/attempt-never-index-test.js
Labels: Internal

#9038 Remove EMBER_CLI_DELAYED_TRANSPILATION experiment.
  .github/workflows/ci.yml
  .travis.yml
  lib/broccoli/ember-app.js
  lib/experiments/index.js
  lib/models/addon.js
  package.json
  tests/unit/broccoli/ember-app/app-and-dependencies-test.js
  tests/unit/broccoli/template-precompilation-test.js
  tests/unit/experiments-test.js
  yarn.lock
Labels: Internal

#9040 Remove MODULE_UNIFICATION experiment.
  .github/workflows/ci.yml
  .travis.yml
  blueprints/in-repo-addon/index.js
  blueprints/packages/index.js
  docs/experiments.md
  lib/broccoli/default-packager.js
  lib/broccoli/ember-addon.js
  lib/broccoli/ember-app.js
  lib/commands/init.js
  lib/experiments/index.js
  lib/models/addon.js
  lib/models/project.js
  lib/utilities/ember-app-utils.js
  package.json
  tests/acceptance/addon-generate-test.js
  tests/acceptance/addon-smoke-test-slow.js
  tests/acceptance/brocfile-smoke-test-slow.js
  tests/acceptance/nested-addons-smoke-test-slow.js
  tests/acceptance/preprocessor-smoke-test-slow.js
  tests/acceptance/smoke-test-slow.js
  tests/fixtures/addon/with-blueprint-override/blueprints/component/index.js
  tests/fixtures/help/generate-with-addon.txt
  tests/fixtures/help/generate.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
  tests/helpers/default-packager.js
  tests/helpers/mock-project.js
  tests/unit/blueprints/packages-test.js
  tests/unit/broccoli/default-packager/ember-cli-internal-test.js
  tests/unit/broccoli/default-packager/index-test.js
  tests/unit/broccoli/default-packager/javascript-test.js
  tests/unit/broccoli/default-packager/process-test.js
  tests/unit/broccoli/default-packager/styles-test.js
  tests/unit/broccoli/default-packager/tests-test.js
  tests/unit/broccoli/ember-app-test.js
  tests/unit/experiments-test.js
  tests/unit/models/project-test.js
  tests/unit/utilities/ember-app-utils-test.js
  yarn.lock
Labels: Internal, breaking

#9045 add final newline in CONTRIBUTING.md
  blueprints/addon/files/CONTRIBUTING.md
  tests/fixtures/addon/npm/CONTRIBUTING.md
  tests/fixtures/addon/yarn/CONTRIBUTING.md
Labels: Bug

#9044 Refactor Blueprint model to avoid floating promises in `_process`.
  lib/models/blueprint.js
Labels: Bug

#9042 Include API documentation `yuidoc` JSON output when publishing
  .npmignore
  package.json
Labels: Documentation

#9070 fail tests on unhandled rejections
  lib/tasks/addon-install.js
  lib/tasks/server/middleware/history-support/index.js
  lib/tasks/server/middleware/tests-server/index.js
  lib/utilities/open-editor.js
  package.json
  tests/integration/models/blueprint-test.js
  tests/runner.js
  tests/unit/docs-lint-test.js
  tests/unit/tasks/addon-install-test.js
  tests/unit/tasks/git-init-test.js
  tests/unit/tasks/server/livereload-server-test.js
  tests/unit/tasks/server/middleware/tests-server-test.js
  tests/unit/utilities/open-editor-test.js
Labels: On-going investigation
