Repository ember-cli/ember-cli, pull requests merged in 2020-10, with the labels that each got.

#9338 Remove requirement to have `loader.js`.
  lib/broccoli/ember-app.js
  tests/unit/broccoli/ember-app-test.js
Labels: internal

#9360 Update blueprint dependencies to latest version.
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9336 Fixup internal test harness fixturify-project helper.
  tests/helpers/fixturify-project.js
Labels: internal

#9361 Update Babel to latest.
  blueprints/app/files/package.json
  package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
  yarn.lock
Labels: enhancement

#9362 Update eslint packages to latest.
  package.json
  yarn.lock
Labels: internal

#9364 Update dependencies to latest within range.
  package.json
  yarn.lock
Labels: enhancement

#9365 Update resolve-package-path to latest.
  package.json
  yarn.lock
Labels: dependencies

#9367 Update supertest to latest.
  package.json
  yarn.lock
Labels: dependencies

#9368 Update markdown-it to latest.
  package.json
  yarn.lock
Labels: dependencies

#9369 Update ember-source and ember-data for 3.23.0-beta's.
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: dependencies

#9371 Adds missing qunit-dom setup invocation
  blueprints/app/files/tests/test-helper.js
Labels: bug
