Repository ember-cli/ember-cli, pull requests merged in 2020-03, with the labels that each got.

#9080 Run basic tests against Windows, Linux, and macOS in GH Actions
  .github/workflows/ci.yml
  tests/acceptance/missing-before-addon-test.js
  tests/runner.js
  tests/unit/broccoli/builder-test.js
  tests/unit/commands/generate-test.js
  tests/unit/tasks/server/express-server-test.js
Labels: Internal

#9087 Remove `actions/cache` from CI.
  .github/workflows/ci.yml
Labels: Internal

#9091 Update app and addon blueprints to latest dependency versions.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9092 Update ember-source and ember-data to 3.18 betas.
  blueprints/app/files/package.json
  tests/fixtures/addon/npm/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9093 Migrate supported Node version detection to use GitHub Actions config.
  .npmignore
  docs/node-support.md
  lib/utilities/platform-checker.js
  tests/unit/utilities/load-config-test.js
  tests/unit/utilities/platform-checker-test.js
Labels: internal

#9094 Update `eslint` and related dependencies.
  .eslintrc.js
  lib/broccoli/ember-app.js
  lib/models/command.js
  package.json
  tests/helpers/package-cache.js
  yarn.lock
Labels: internal

#9095 Remove AppVeyor CI.
  README.md
  appveyor.yml
  tests/unit/broccoli/builder-test.js
  tests/unit/commands/generate-test.js
  tests/unit/commands/test-test.js
  tests/unit/models/builder-test.js
  tests/unit/models/command-test.js
Labels: internal

#9097 Update production dependencies to latest.
  lib/models/file-info.js
  package.json
  yarn.lock
Labels: enhancement

#9098 Add GitHub Actions badge to README.md.
  README.md
Labels: documentation

#9099 Migrate CI to use actions/checkout@v2.
  .github/workflows/ci.yml
Labels: internal

#9101 Migrate code coverage to GitHub Actions.
  .codeclimate.yml
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .nycrc.json
  .travis.yml
  .travis/codecoverage.sh
  package.json
Labels: internal

#9102 Remove TravisCI setup.
  .travis.yml
  .travis/deploy.sh
  .travis/deploy_key.pem.enc
  .travis/deploy_key.pem.pub
  README.md
  docs/build-concurrency.md
  docs/code-coverage.md
  tests/fixtures/smoke-tests/js-testem-config/testem.js
Labels: internal

#9103 Re-roll yarn.lock.
  package.json
  tests/helpers/has-global-yarn.js
  tests/helpers/proxy-server.js
  yarn.lock
Labels: internal

#8813 Update NPM version check to avoid double `npm install` when using `npm@5.7.1` or higher.
  lib/tasks/npm-task.js
Labels: enhancement

#9116 Update paambaati/codeclimate-action to v2.5.5.
  .github/workflows/coverage.yml
Labels: internal

#9108 Cleanup of async in `CLI` / `Builder` while digging into issues around progress clean up.
  lib/cli/cli.js
  lib/cli/index.js
  lib/models/builder.js
  lib/tasks/build.js
  tests/unit/cli/cli-test.js
  tests/unit/models/builder-test.js
Labels: bug
