Repository ember-cli/ember-cli, pull requests merged in 2020-07, with the labels that each got.

#9280 Remove `ember-default` ember-try scenario
  blueprints/addon/files/addon-config/ember-try.js
  tests/fixtures/addon/defaults/config/ember-try.js
  tests/fixtures/addon/yarn/config/ember-try.js
Labels: bug

#9283 Remove macOS from CI matrix for slow/acceptance tests.
  .github/workflows/ci.yml
Labels: internal

#9281 Update blueprint dependencies to latest versions.
  blueprints/app/files/package.json
  dev/update-blueprint-dependencies.js
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9282 Deprecate `PACKAGER` experiment.
  lib/experiments/index.js
  tests/unit/experiments-test.js
Labels: documentation

#9289 Update blueprint dependencies / devDependencies
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#9263 Use workers to print asset sizes for production builds
  lib/models/asset-size-printer.js
  lib/models/gzipStats.js
  lib/models/worker.js
  package.json
  yarn.lock
Labels: enhancement
