Repository ember-cli/ember-cli, pull requests merged in 2021-03, with the labels that each got.

#9457 Enable Embroider tests with new Dist Checker
  package.json
  tests/acceptance/preprocessor-smoke-test-slow.js
  tests/fixtures/preprocessor-tests/app-with-addon-with-preprocessors-2/app/components/should-not-be-preprocessed.js
  tests/fixtures/preprocessor-tests/app-with-addon-with-preprocessors-2/node_modules/ember-cool-addon/addon/components/clitest-example.js
  tests/fixtures/preprocessor-tests/app-with-addon-with-preprocessors-3/app/components/should-not-be-preprocessed.js
  tests/helpers/dist-checker.js
  yarn.lock
Labels: internal

#9469 [FEATURE] Lint fix after blueprint generation
  lib/commands/generate.js
  lib/commands/init.js
  lib/tasks/generate-from-blueprint.js
  lib/tasks/install-blueprint.js
  lib/utilities/lint-fix.js
  tests/acceptance/generate-test.js
  tests/acceptance/init-test.js
  tests/acceptance/smoke-test-slow.js
  tests/fixtures/app/with-blueprint-override-lint-fail/.eslintrc.js
  tests/fixtures/app/with-blueprint-override-lint-fail/.prettierrc.js
  tests/fixtures/app/with-blueprint-override-lint-fail/.template-lintrc.js
  tests/fixtures/app/with-blueprint-override-lint-fail/.travis.yml
  tests/fixtures/app/with-blueprint-override-lint-fail/README.md
  tests/fixtures/app/with-blueprint-override-lint-fail/app/templates/application.hbs
  tests/fixtures/app/with-blueprint-override-lint-fail/blueprints/component/files/__root__/__path__/__name__.hbs
  tests/fixtures/app/with-blueprint-override-lint-fail/blueprints/component/files/__root__/__path__/__name__.js
  tests/fixtures/app/with-blueprint-override-lint-fail/config/ember-cli-update.json
  tests/fixtures/app/with-blueprint-override-lint-fail/ember-cli-build.js
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/help/generate-blueprint.txt
  tests/fixtures/help/generate-with-addon.txt
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
  tests/helpers/ember.js
Labels: enhancement

#9474 Bump embroider to 0.37.0
  blueprints/addon/additional-dev-dependencies.json
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
Labels: dependencies

#9481 Pin QUnit to 2.13.0 due to strict mode regression in 2.14.0.
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn/package.json
Labels: bug

#9482 Fix support for filtering in internal `dev/update-blueprint-dependencies.js` script
  dev/update-blueprint-dependencies.js
Labels: internal

#9480 Refactor getPort to only check required port
  lib/commands/serve.js
Labels: enhancement

#9490 Prevent window.Ember deprecation on Ember 3.27+.
  lib/utilities/ember-app-utils.js
  tests/unit/utilities/ember-app-utils-test.js
Labels: bug

#9491 Update supported Ember CLI version in addon blueprint
  blueprints/addon/files/README.md
  tests/fixtures/addon/defaults/README.md
  tests/fixtures/addon/yarn/README.md
Labels: bug

#9495 Enable Embroider by default for new projects
  blueprints/addon/additional-dev-dependencies.json
  blueprints/app/files/package.json
  lib/experiments/index.js
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
Labels: enhancement

#9500 Implemented one-line fix for yarn lint not working in Windows (+ test fixtures)
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn/package.json
Labels: bug
