Repository ember-cli/ember-cli, pull requests merged in 2022-10, with the labels that each got.

#10038 Update `filesize` to v10
  lib/models/asset-size-printer.js
  package.json
  yarn.lock
Labels: dependencies

#10017 [ENHANCEMENT] Disable prototype extensions by default in `app` blueprint
  blueprints/addon/additional-package.json
  blueprints/app/files/config/environment.js
  tests/fixtures/addon/defaults-travis/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/unit/blueprints/addon-test.js
Labels: enhancement

#10041 [INTERNAL] Remove end year from copyright notice
  LICENSE
Labels: internal

#10026 [ENHANCEMENT] Display info message when running the `lint:fix` script post blueprint generation
  lib/tasks/generate-from-blueprint.js
  lib/tasks/install-blueprint.js
  lib/utilities/lint-fix.js
Labels: enhancement

#10049 [ENHANCEMENT] Remove the `config/environment.js` file from the `addon` blueprint
  blueprints/addon/files/addon-config/environment.js
  blueprints/addon/index.js
  tests/acceptance/addon-smoke-test-slow.js
Labels: enhancement

#10051 [ENHANCEMENT] Move `ember-try.js` config file to `tests/dummy/config/ember-try.js` for addons
  blueprints/addon/files/npmignore
  blueprints/addon/index.js
  tests/acceptance/new-test.js
  tests/fixtures/addon/defaults-travis/tests/dummy/config/ember-try.js
  tests/fixtures/addon/defaults/tests/dummy/config/ember-try.js
  tests/fixtures/addon/yarn/tests/dummy/config/ember-try.js
Labels: enhancement

#10054 [ENHANCEMENT] Conditionally apply eslint parserOptions
  blueprints/app/files/.eslintrc.js
  tests/fixtures/addon/typescript/.eslintrc.js
  tests/fixtures/app/typescript-embroider/.eslintrc.js
  tests/fixtures/app/typescript/.eslintrc.js
Labels: enhancement

#10062 [ENHANCEMENT] Update the Prettier config in the blueprints
  blueprints/app/files/.prettierrc.js
Labels: enhancement
