Repository ember-cli/ember-cli, pull requests merged in 2022-12, with the labels that each got.

#10101 [BUGFIX release] Correctly instantiate `Watcher` instance when running `ember test --serve`
  lib/commands/test.js
  tests/unit/commands/test-test.js
Labels: bug

#10108 [BUGFIX release] Correctly instantiate server watcher
  lib/models/server-watcher.js
  lib/tasks/serve.js
  tests/unit/models/server-watcher-test.js
Labels: bug

#10109 [RFC 811] Add `ember-modifier` dependency to app blueprint
  blueprints/addon/index.js
  blueprints/app/files/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm-travis/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn-travis/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#10104 [INTERNAL] Remove `greenkeeper` entry from `package.json` file
  package.json
Labels: internal

#10105 [INTERNAL] Remove `BROCCOLI_WATCHER` from deprecated experiments
  lib/experiments/index.js
Labels: internal
