Repository ember-cli/ember-cli, pull requests merged in 2022-08, with the labels that each got.

#9951 Update `js-yaml` to v4
  lib/utilities/load-config.js
  package.json
  yarn.lock
Labels: dependencies

#9952 Update `walk-sync` to v3
  package.json
  yarn.lock
Labels: dependencies

#9987 Handle rebuild failures without exiting
  lib/models/builder.js
  lib/tasks/server/middleware/history-support/index.js
  tests/unit/models/builder-test.js
Labels: bug

#9945 [ENHANCEMENT/BREAKING] Add Node v18 to `engines` in `app` and `addon` blueprint (removes support for Node v17)
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults-travis/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/nested-project/actual-project/package.json
  tests/fixtures/app/npm-travis/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn-travis/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement, breaking

#9946 [INTERNAL] Unskip `package-info-cache` tests
  tests/unit/commands/show-asset-sizes-test.js
  tests/unit/models/package-info-cache/package-info-cache-test.js
Labels: internal

#9920 [BUGFIX] Make sure a blueprint’s options object and project instance are always available for all public hooks
  lib/models/blueprint.js
  lib/tasks/generate-from-blueprint.js
Labels: bug
