Repository ember-cli/ember-cli, pull requests merged in 2023-04, with the labels that each got.

#10232 [CLEANUP] Remove Babel fallback for addons
  lib/broccoli/babel-process-modules-only.js
  lib/models/addon.js
  package.json
  tests/acceptance/preprocessor-smoke-test-slow.js
  tests/fixtures/addon/with-nested-addons/node_modules/ember-top-addon/node_modules/ember-inner-addon/package.json
  tests/fixtures/addon/with-nested-addons/node_modules/ember-top-addon/package.json
  tests/fixtures/preprocessor-tests/app-with-addon-with-preprocessors-3/node_modules/ember-shallow-addon/package.json
  tests/fixtures/preprocessor-tests/app-with-addon-with-preprocessors/node_modules/ember-cool-addon/package.json
  tests/fixtures/preprocessor-tests/app-with-addon-without-preprocessors/app/styles/app.scss
  tests/fixtures/preprocessor-tests/app-with-addon-without-preprocessors/node_modules/ember-cool-addon/addon/styles/addon.css
  tests/fixtures/preprocessor-tests/app-with-addon-without-preprocessors/node_modules/ember-cool-addon/index.js
  tests/fixtures/preprocessor-tests/app-with-addon-without-preprocessors/node_modules/ember-cool-addon/package.json
  tests/unit/models/addon-test.js
  yarn.lock
Labels: breaking, v5.0

#10229 Update blueprint ignore files
  blueprints/app/files/.eslintignore
  blueprints/app/files/.prettierignore
  blueprints/app/files/.watchmanconfig
  blueprints/app/files/gitignore
Labels: v5.0

#10251 [BUGFIX release] Remove `stylelint-config-prettier` from `app` blueprint
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults-travis/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/nested-project/actual-project/package.json
  tests/fixtures/app/npm-travis/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn-travis/package.json
  tests/fixtures/app/yarn/package.json
Labels: bug

#10256 [ENHANCEMENT] Align `hbs` templates generated by `app` blueprint with Prettier defaults
  blueprints/app/files/app/templates/application.hbs
  tests/fixtures/addon/yarn/tests/dummy/app/templates/application.hbs
  tests/fixtures/app/defaults/app/templates/application.hbs
  tests/fixtures/app/nested-project/actual-project/app/templates/application.hbs
  tests/fixtures/app/with-blueprint-override-lint-fail/app/templates/application.hbs
  tests/fixtures/app/yarn-travis/app/templates/application.hbs
  tests/fixtures/app/yarn/app/templates/application.hbs
Labels: enhancement, blueprints
