Repository ember-cli/ember-cli, pull requests merged in 2023-02, with the labels that each got.

#10091 [BUGFIX] Fix looking up the default blueprint for scoped addons
  lib/models/blueprint.js
  tests/acceptance/addon-generate-test.js
  tests/acceptance/generate-test.js
Labels: bug

#10157 [ENHANCEMENT] Exclude `ember-cli-terser` when generating apps using the `--embroider` option
  blueprints/app/files/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
Labels: enhancement, blueprints

#10166 [INTERNAL] Remove unused dependencies
  package.json
  yarn.lock
Labels: internal

#10161 [ENHANCEMENT] Remove NPM version checking
  lib/tasks/npm-task.js
  tests/unit/tasks/npm-task-test.js
Labels: enhancement

#10169 [ENHANCEMENT] Remove `app.import` comment in `app` blueprint
  blueprints/app/files/ember-cli-build.js
  tests/fixtures/app/defaults/ember-cli-build.js
  tests/fixtures/app/embroider/ember-cli-build.js
  tests/fixtures/app/nested-project/actual-project/ember-cli-build.js
  tests/fixtures/app/with-blueprint-override-lint-fail/ember-cli-build.js
Labels: enhancement

#10173 [ENHANCEMENT] Don't delete the newly-generated app directory when an error occurs
  lib/commands/new.js
  tests/acceptance/new-test.js
Labels: enhancement

#10172 [PERFORMANCE] Lazy require heavier packages
  lib/commands/test.js
  lib/models/blueprint.js
  lib/tasks/interactive-new.js
  lib/tasks/transforms/amd/index.js
Labels: performance

#10174 [INTERNAL] Clean up removal of `bower.json` and `package.json` files in `addon` blueprint
  blueprints/addon/index.js
Labels: internal

#10180 [ENHANCEMENT] Update `ember-welcome-page` to v7 in `app` blueprint
  blueprints/app/files/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#10159 [ENHANCEMENT] Exclude `ember-cli-sri` when generating apps using the `--embroider` option
  blueprints/app/files/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
Labels: enhancement, blueprints, embroider

#10188 [ENHANCEMENT] Update ESLint parser `ecmaVersion` to `latest` in `app` blueprint
  blueprints/app/files/.eslintrc.js
  tests/fixtures/addon/.eslintrc.js
  tests/fixtures/addon/typescript/.eslintrc.js
  tests/fixtures/app/.eslintrc.js
  tests/fixtures/app/typescript-embroider/.eslintrc.js
  tests/fixtures/app/typescript/.eslintrc.js
  tests/fixtures/app/with-blueprint-override-lint-fail/.eslintrc.js
Labels: enhancement, blueprints

#10192 [BUGFIX] The `addon` command should throw when no addon name is provided
  lib/commands/addon.js
  tests/unit/commands/addon-test.js
Labels: bug

#10189 [ENHANCEMENT] Add v4.8 LTS to `addon` blueprint - Remove v3.28 LTS and `ember-classic` scenario
  blueprints/addon/additional-package.json
  blueprints/addon/files/.github/workflows/ci.yml
  blueprints/addon/files/.travis.yml
  blueprints/addon/files/README.md
  blueprints/addon/files/addon-config/ember-try.js
  tests/fixtures/addon/defaults-travis/.travis.yml
  tests/fixtures/addon/defaults-travis/README.md
  tests/fixtures/addon/defaults-travis/tests/dummy/config/ember-try.js
  tests/fixtures/addon/defaults/.github/workflows/ci.yml
  tests/fixtures/addon/defaults/README.md
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/defaults/tests/dummy/config/ember-try.js
  tests/fixtures/addon/yarn/.github/workflows/ci.yml
  tests/fixtures/addon/yarn/.travis.yml
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/addon/yarn/tests/dummy/config/ember-try.js
  tests/unit/blueprints/addon-test.js
Labels: enhancement, blueprints

#10198 [INTERNAL] Output TypeScript apps and addons for StackBlitz
  dev/update-output-repos.js
  package.json
Labels: internal

#10199 [INTERNAL] Update action versions in `Code Coverage` workflow
  .github/workflows/coverage.yml
Labels: internal
