Repository ember-cli/ember-cli, pull requests merged in 2024-12, with the labels that each got.

#10577 [ENHANCEMENT] Remove `@ember/string` from `app` blueprint
  blueprints/addon/index.js
  blueprints/app/files/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement, blueprints

#10579 [INTERNAL] Update `sort-package-json`
  blueprints/addon/index.js
  package.json
  pnpm-lock.yaml
Labels: internal, dependencies

#10578 [ENHANCEMENT] Test against Node v22
  .github/workflows/ci.yml
  docs/node-support.md
Labels: enhancement

#10580 [ENHANCEMENT] Update LTS versions in blueprints
  blueprints/addon/files/.github/workflows/ci.yml
  blueprints/addon/files/README.md
  blueprints/addon/files/addon-config/ember-try.js
  tests/fixtures/addon/defaults-travis/README.md
  tests/fixtures/addon/defaults-travis/tests/dummy/config/ember-try.js
  tests/fixtures/addon/defaults/.github/workflows/ci.yml
  tests/fixtures/addon/defaults/README.md
  tests/fixtures/addon/defaults/tests/dummy/config/ember-try.js
  tests/fixtures/addon/pnpm/.github/workflows/ci.yml
  tests/fixtures/addon/pnpm/README.md
  tests/fixtures/addon/pnpm/tests/dummy/config/ember-try.js
  tests/fixtures/addon/yarn/.github/workflows/ci.yml
  tests/fixtures/addon/yarn/README.md
  tests/fixtures/addon/yarn/tests/dummy/config/ember-try.js
Labels: enhancement, blueprints

#10582 [CLEANUP] Remove `@typescript-eslint/*` dependencies from `app` blueprint
  blueprints/app/files/package.json
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
Labels: blueprints

#10584 [INTERNAL] Set `packageManager` in `package.json`
  .github/actions/setup-environment/action.yml
  .github/workflows/ci.yml
  package.json
Labels: internal

#10585 [INTERNAL] Support `WRITE_FIXTURES` in more test files
  tests/acceptance/new-test.js
Labels: internal

#10583 [ENHANCEMENT] Update `app` blueprint to support `ember-qunit` v9
  blueprints/app/files/package.json
  blueprints/app/files/tests/test-helper.ts
  pnpm-lock.yaml
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/pnpm/package.json
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement, blueprints

#10592 [BUGFIX] Fix ESLint config for v1 addons
  blueprints/app/files/_js_eslint.config.mjs
  blueprints/app/files/_ts_eslint.config.mjs
  tests/fixtures/addon/eslint.config.mjs
  tests/fixtures/addon/typescript/eslint.config.mjs
  tests/fixtures/app/eslint.config.mjs
  tests/fixtures/app/typescript-embroider/eslint.config.mjs
  tests/fixtures/app/typescript/eslint.config.mjs
  tests/fixtures/app/with-blueprint-override-lint-fail/eslint.config.mjs
Labels: bug

#10587 [BUGFIX] Fix including `ember-source` types for v1 addons
  blueprints/addon/files/tsconfig.json
  tests/fixtures/addon/typescript/tsconfig.json
Labels: bug

#10586 [INTERNAL] Add tests to ensure no linting errors post generating a new app or addon
  .github/workflows/ci.yml
  tests/acceptance/new-test-slow.js
Labels: internal

#10534 [CLEANUP] Clean up `outputPaths` deprecation
  lib/broccoli/ember-app.js
  lib/debug/deprecations.js
  tests/acceptance/brocfile-smoke-test-slow.js
  tests/fixtures/brocfile-tests/custom-output-paths/ember-cli-build.js
  tests/fixtures/brocfile-tests/multiple-sass-files/ember-cli-build.js
Labels: breaking, v6.0

#10538 [CLEANUP] Clean up Travis CI deprecation
  blueprints/addon/files/.travis.yml
  blueprints/addon/files/npmignore
  blueprints/addon/index.js
  blueprints/app/files/.travis.yml
  blueprints/app/index.js
  docs/build-concurrency.md
  lib/commands/addon.js
  lib/commands/init.js
  lib/commands/new.js
  lib/debug/deprecations.js
  lib/tasks/interactive-new.js
  tests/acceptance/addon-smoke-test-slow.js
  tests/acceptance/init-test.js
  tests/acceptance/new-test.js
  tests/acceptance/smoke-test-slow.js
  tests/fixtures/addon/defaults-travis/.travis.yml
  tests/fixtures/addon/defaults-travis/CONTRIBUTING.md
  tests/fixtures/addon/defaults-travis/tests/dummy/app/templates/application.hbs
  tests/fixtures/addon/defaults-travis/tests/dummy/config/ember-cli-update.json
  tests/fixtures/addon/yarn/.travis.yml
  tests/fixtures/app/npm-travis-embroider/config/ember-cli-update.json
  tests/fixtures/app/npm-travis/.travis.yml
  tests/fixtures/app/npm-travis/README.md
  tests/fixtures/app/npm-travis/app/templates/application.hbs
  tests/fixtures/app/npm-travis/config/ember-cli-update.json
  tests/fixtures/app/with-blueprint-override-lint-fail/.travis.yml
  tests/fixtures/app/yarn-travis-embroider/config/ember-cli-update.json
  tests/fixtures/app/yarn-travis/.travis.yml
  tests/fixtures/app/yarn-travis/README.md
  tests/fixtures/app/yarn-travis/app/templates/application.hbs
  tests/fixtures/app/yarn-travis/config/ember-cli-update.json
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
  tests/unit/commands/new-test.js
Labels: breaking, v6.0

#10595 [ENHANCEMENT] Update `@glimmer/component` to v2 in blueprints
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/pnpm/package.json
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/nested-project/actual-project/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement, blueprints
