Repository ember-cli/ember-cli, pull requests merged in 2025-01, with the labels that each got.

#10599 [INTERNAL] Bump `content-tag` to v3
  package.json
  pnpm-lock.yaml
Labels: internal, dependencies

#10615 [ENHANCEMENT] Simplify Prettier config in blueprints
  blueprints/app/files/.prettierrc.js
Labels: enhancement, blueprints

#10616 [INTERNAL] Add test to ensure all package files are parseable
  dev/update-blueprint-dependencies.js
  tests/unit/dev/update-blueprint-dependencies-test.js
Labels: internal

#10617 [ENHANCEMENT] Use `staticInvokables` in the `app` blueprint
  blueprints/app/files/ember-cli-build.js
  blueprints/app/files/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/ember-cli-build.js
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/typescript-embroider/ember-cli-build.js
  tests/fixtures/app/typescript-embroider/package.json
Labels: enhancement, blueprints

#10596 [ENHANCEMENT] Vanilla Prettier setup in blueprints [RFC 1055]
  blueprints/addon/files/tsconfig.json
  blueprints/app/files/.prettierignore
  blueprints/app/files/.stylelintrc.js
  blueprints/app/files/_js_eslint.config.mjs
  blueprints/app/files/_ts_eslint.config.mjs
  blueprints/app/files/package.json
  lib/commands/addon.js
  lib/commands/new.js
  tests/acceptance/new-test-slow.js
  tests/acceptance/smoke-test-slow.js
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/eslint.config.mjs
  tests/fixtures/addon/pnpm/package.json
  tests/fixtures/addon/typescript/eslint.config.mjs
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/addon/typescript/tsconfig.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/eslint.config.mjs
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/eslint.config.mjs
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/eslint.config.mjs
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/with-blueprint-override-lint-fail/blueprints/component/files/__root__/__path__/__name__.js
  tests/fixtures/app/with-blueprint-override-lint-fail/eslint.config.mjs
  tests/fixtures/app/yarn/package.json
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
Labels: enhancement, blueprints

#10589 [ENHANCEMENT] Deprecate v1 addon `contentFor` types [RFC 1044]
  lib/debug/deprecate.js
  lib/debug/deprecations.js
  lib/utilities/ember-app-utils.js
  tests/unit/broccoli/default-packager/ember-cli-internal-test.js
  tests/unit/utilities/ember-app-utils-test.js
Labels: enhancement

#10618 [INTERNAL] Avoid output for `deprecate` tests
  lib/debug/deprecate.js
  tests/unit/debug/deprecate-test.js
Labels: internal

#10588 [ENHANCEMENT] Add `ember-cli-deprecation-workflow` to `app` blueprint [RFC 1009]
  blueprints/app/files/app/app.ts
  blueprints/app/files/app/deprecation-workflow.ts
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/pnpm/package.json
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement

#10621 [ENHANCEMENT] Bump `@ember/test-helpers` to v5.1.0 in blueprints
  blueprints/app/files/package.json
  tests/fixtures/addon/defaults/package.json
  tests/fixtures/addon/pnpm/package.json
  tests/fixtures/addon/typescript/package.json
  tests/fixtures/addon/yarn/package.json
  tests/fixtures/app/defaults/package.json
  tests/fixtures/app/embroider-no-welcome/package.json
  tests/fixtures/app/embroider-pnpm/package.json
  tests/fixtures/app/embroider-yarn/package.json
  tests/fixtures/app/embroider/package.json
  tests/fixtures/app/npm/package.json
  tests/fixtures/app/pnpm/package.json
  tests/fixtures/app/typescript-embroider/package.json
  tests/fixtures/app/typescript/package.json
  tests/fixtures/app/yarn/package.json
Labels: enhancement, blueprints
