Repository ember-cli/ember-cli, pull requests merged in 2025-08, with the labels that each got.

#10750 Add more notes to the Release.md
  RELEASE.md
Labels: internal

#10782 update heimdall-fs-monitor
  package.json
  pnpm-lock.yaml
Labels: dependencies

#10776 Add deprecation warning for the `--embroider` argument
  lib/commands/init.js
  lib/commands/new.js
  lib/debug/deprecations.js
  tests/acceptance/new-test.js
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
Labels: enhancement
