Repository ember-cli/ember-cli, pull requests merged in 2025-09, with the labels that each got.

#10790 Reorganize tests for `new` and `addon` commands
  tests/acceptance/addon-dummy-generate-test.js
  tests/acceptance/addon-test-slow.js
  tests/acceptance/addon-test.js
  tests/acceptance/new-test-slow.js
  tests/acceptance/new-test.js
  tests/helpers-internal/file-utils.js
  tests/helpers-internal/fixtures.js
Labels: internal

#10791 update the format of the ember-cli-update.json
  packages/addon-blueprint/index.js
  packages/app-blueprint/files/config/ember-cli-update.json
  packages/app-blueprint/index.js
  tests/acceptance/addon-test.js
  tests/acceptance/new-test.js
  tests/fixtures/addon/defaults/tests/dummy/config/ember-cli-update.json
  tests/fixtures/addon/pnpm/tests/dummy/config/ember-cli-update.json
  tests/fixtures/addon/typescript/tests/dummy/config/ember-cli-update.json
  tests/fixtures/addon/yarn/tests/dummy/config/ember-cli-update.json
  tests/fixtures/app/defaults/config/ember-cli-update.json
  tests/fixtures/app/embroider-no-ember-data/config/ember-cli-update.json
  tests/fixtures/app/embroider-no-welcome/config/ember-cli-update.json
  tests/fixtures/app/embroider-pnpm/config/ember-cli-update.json
  tests/fixtures/app/embroider-yarn/config/ember-cli-update.json
  tests/fixtures/app/embroider/config/ember-cli-update.json
  tests/fixtures/app/no-ember-data/config/ember-cli-update.json
  tests/fixtures/app/npm/config/ember-cli-update.json
  tests/fixtures/app/pnpm/config/ember-cli-update.json
  tests/fixtures/app/typescript-embroider-no-ember-data/config/ember-cli-update.json
  tests/fixtures/app/typescript-embroider/config/ember-cli-update.json
  tests/fixtures/app/typescript-no-ember-data/config/ember-cli-update.json
  tests/fixtures/app/typescript/config/ember-cli-update.json
  tests/fixtures/app/with-blueprint-override-lint-fail/config/ember-cli-update.json
  tests/fixtures/app/yarn/config/ember-cli-update.json
  tests/helpers-internal/fixtures.js
Labels: enhancement

#10778 Prepare Alpha Release
  .release-plan.json
  CHANGELOG.md
  package.json
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
Labels: internal

#10795 Prepare Alpha Release
  .release-plan.json
  CHANGELOG.md
  package.json
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
  packages/blueprint-model/package.json
Labels: internal

#10798 Add import from ember-data breakage/deprecation
  packages/app-blueprint/files/app/app.ts
Labels: bug

#10800 fix release-plan for stable release
  .github/workflows/plan-stable-release.yml
  packages/addon-blueprint/package.json
  packages/app-blueprint/package.json
  pnpm-workspace.yaml
Labels: internal

#10797 Prepare Stable Release
  .release-plan.json
  CHANGELOG.md
  package.json
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
Labels: internal

#10804 Support a `--ts` alias for the `addon`, `init` and `new` commands
  lib/commands/addon.js
  lib/commands/init.js
  lib/commands/new.js
  tests/fixtures/help/help-with-addon.txt
  tests/fixtures/help/help.js
  tests/fixtures/help/help.txt
  tests/fixtures/help/with-addon-blueprints.js
  tests/fixtures/help/with-addon-commands.js
Labels: enhancement

#10806 skip build watch tests when vite is enabled
  tests/acceptance/smoke-test-slow.js
Labels: internal

#10802 enable Vite by default
  packages/blueprint-model/utilities/experiments.js
Labels: enhancement

#10810 Prepare Beta Release
  .release-plan.json
  CHANGELOG.md
  package.json
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
  packages/blueprint-blueprint/package.json
  packages/blueprint-model/package.json
Labels: internal

#10816 Prepare Alpha Release
  .release-plan.json
  CHANGELOG.md
  package.json
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
  packages/blueprint-blueprint/package.json
  packages/blueprint-model/package.json
Labels: internal

#10809 Update RELEASE
  RELEASE.md
Labels: internal
