Repository ember-cli/ember-cli, pull requests merged in 2025-06, with the labels that each got.

#10701 [ENHANCEMENT] Support Bun
  lib/utilities/will-interrupt-process.js
Labels: enhancement

#10710 make sure we release alpha with release-plan
  package.json
  tests/acceptance/new-test-slow.js
Labels: bug

#10715 [Backport beta]: Set up release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
  tests/unit/models/package-info-cache/package-info-cache-test.js
Labels: internal

#10726 use patched github-changelog for properly rolling up beta changelog
  package.json
  pnpm-lock.yaml
Labels: internal

#10724 Update RELEASE.md to fully document new release-plan setup
  RELEASE.md
Labels: documentation

#10736 update all sub-packages to have the @ember-tooling prefix
  lib/commands/init.js
  lib/models/blueprint.js
  lib/tasks/create-and-step-into-directory.js
  lib/tasks/git-init.js
  lib/tasks/npm-task.js
  lib/utilities/lint-fix.js
  package.json
  packages/addon-blueprint/index.js
  packages/addon-blueprint/package.json
  packages/app-blueprint/index.js
  packages/app-blueprint/package.json
  packages/blueprint-blueprint/package.json
  packages/blueprint-model/package.json
  pnpm-lock.yaml
  tests/acceptance/brocfile-smoke-test-slow.js
  tests/acceptance/init-test.js
  tests/acceptance/new-test.js
  tests/acceptance/smoke-test-slow.js
  tests/fixtures/addon/with-blueprint-override/blueprints/component/index.js
  tests/fixtures/brocfile-tests/additional-trees/ember-cli-build.js
  tests/fixtures/brocfile-tests/app-import-anonymous-amd/ember-cli-build.js
  tests/fixtures/brocfile-tests/app-import-custom-transform/ember-cli-build.js
  tests/fixtures/brocfile-tests/app-import-named-umd/ember-cli-build.js
  tests/fixtures/brocfile-tests/app-import-output-file/ember-cli-build.js
  tests/fixtures/brocfile-tests/auto-run-false/ember-cli-build.js
  tests/fixtures/brocfile-tests/auto-run-true/ember-cli-build.js
  tests/fixtures/brocfile-tests/custom-environment-config/ember-cli-build.js
  tests/fixtures/brocfile-tests/multiple-sass-files/ember-cli-build.js
  tests/integration/models/blueprint-test.js
  tests/unit/blueprints/addon-test.js
  tests/unit/experiments-test.js
  tests/unit/models/file-info-test.js
  tests/unit/utilities/open-editor-test.js
  tests/unit/utilities/process-template-test.js
Labels: internal

#10738 add a repository for each of the packages
  packages/addon-blueprint/package.json
  packages/app-blueprint/files/package.json
  packages/app-blueprint/package.json
  packages/blueprint-blueprint/package.json
  packages/blueprint-model/package.json
Labels: internal
